{
# 公众号配置
# 公众号appId
"app_id":"wxfd20da328440b31d",
# 公众号appSecret
"app_secret":"06d822b99dfe0cb85f55654bac4629bd",
# 模板消息id
"template_id":"bPzdK_1PuBakjFiO4SzK90Fg8TrkqP8aRAuRNlyO4UU",
# 接收公众号消息的微信号，如果有多个，需要在[]里用英文逗号间隔，例如["wx1", "wx2"]
"user":["oU7dj6I5K4f8HCqlFDL3dSX-rYVk”],
 
# 信息配置
# 和风天气apikey
"weather_key":"	
9f4b5971d64c423086deb11172516151",
# 所在地区，可为省，城市，区，县，同时支持国外城市，例如伦敦
"region":"青岛市",
# 生日1，修改名字为对应需要显示的名字，如果生日为农历，在最前面加上r即可
"birthday1":{"name":"波波宝贝", "birthday":"03-24"},
# 生日2
"birthday2":{"name":"叔叔", "birthday":"01-19"},
# 在一起的日子，格式同上，暂不不支持农历
"love_date":"2022-05-19",
# 金句中文，如果设置了，则会显示这里的，如果为空，默认会读取金山的每日金句
"note_ch":"",
# 金句英文
"note_en":""
}

